FROM python:3.10.8-slim

# Prevents python from writing .pyc (compiled byte) codes to disk
ENV PYTHONDONTWRITEBYTECODE 0

# Forces python outputs to be sent straight to terminal, without buffering
ENV PYTHONUNBUFFERED 1

# Indicates whether it's in production or local env and if it's testing
ENV ENVIRONMENT local
ENV TESTING 1

# Install dockerize to ensure availability of container dependencies
RUN apt-get update && apt-get install -y wget
ENV DOCKERIZE_VERSION v0.6.1
RUN wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz \
    && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gzRUN

# Install poetry
RUN curl -sSL https://install.python-poetry.org | POETRY_HOME=/etc/poetry python3 - && \
    poetry config virtualenvs.create true

# Add non-root user
RUN useradd -ms /bin/bash local

USER local

WORKDIR /home/local/fastapi-blog

COPY . .

# Install dependencies
ARG INSTALL_DEV=true
RUN poetry shell && \
    bash -c "if [ $INSTALL_DEV == 'true' ] ; then poetry install --no-root ; \
    else poetry install --no-root --without dev ; fi"

CMD ["tail", "-f", "/dev/null"]