version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    ports:
      - 5432:5432
    volumes:
      - app-db-data:/var/lib/postgresql/data
    networks:
      - app-db-network
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      POSTGRES_DB: "blog"
    restart: on-failure

  pgmyadmin:
    image: dpage/pgadmin4:latest
    container_name: pgmyadmin
    ports:
      - 80:80
    networks:
      - app-db-network
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_USER: "admin"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - db
    restart: on-failure

  backend:
    build:
      context: .
      dockerfile: Dockerfile.local
    container_name: backend
    ports:
      - 8000:8000
    volumes:
      - ./backend/app:/app
    networks:
      - app-db-network
    environment:
      - DB_USER=admin
      - DB_PASSWORD=admin
      - DB_HOST=localhost
      - DB_PORT=5432
      - DB_DATABASE_NAME=blog
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    depends_on:
      - db
    restart: on-failure

volumes:
  app-db-data:
    driver: local

networks:
  app-db-network:
    driver: bridge
