name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Lint and test code base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2.2"]
        app_path: ["backend/app"]
        tests_path: ["backend/tests"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      shell: bash
      run: python -m poetry install --no-root

    - name: Run formatters and linters
      shell: bash
      run: |
        poetry run autoflake ${{ matrix.app_path }}
        poetry run isort ${{ matrix.app_path }}
        poetry run black ${{ matrix.app_path }}
        poetry run mypy ${{ matrix.app_path }}
        poetry run pylint ${{ matrix.app_path }}
        poetry run flake8 ${{ matrix.app_path }}

    - name: Run tests
      shell: bash
      run: poetry run pytest ${{ matrix.tests_path }}