name: CI

on: [push, pull_request]

jobs:
  ci:
    name: Lint and test code base
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.10"]
        poetry-version: ["1.2"]

    steps:
    - uses: actions/checkout@v3

    - name: Set up python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Set up poetry
      uses: abatilo/actions-poetry@v2
      with:
        poetry-version: ${{ matrix.poetry-version }}

    - name: Install dependencies
      shell: bash
      run: poetry install

    - name: Active poetry shell
      shell: bash
      run: poetry shell

    - name: Run formatters and linters
      shell: bash
      run: make lint

    - name: Run tests
      shell: bash
      run: make tests